### ISSUE TITLE
Figure out secure approaches to Docker

### ISSUE THREAD

**Issue by davclark** [dlab-projects/benten-config#2]
Sadly, it turns out that access to docker entails *at least* [giving root access to the end user to the whole filesystem](https://docs.docker.com/engine/articles/security/#docker-daemon-attack-surface).

There is apparently a fix coming "any day now" that uses Linux user namespaces since 2013. I'm a bit out of my depth here, but I'm guessing we may have to do some heinous thing like docker inside docker to support the broad use of docker on this machine...

For now, I'm proposing that we simply *not use Docker* in mainline analysis, but move towards that as a research project this semester.

cc @aculich @cboettig @CyrusDioun @carpetfizz

**Comment by davclark** [comment]
Apparently user namespaces are now slated to hit release in [February 2016](https://integratedcode.us/2015/10/13/user-namespaces-have-arrived-in-docker/).

**Comment by cboettig** [comment]
Right.  The typical pattern I see is still to isolate users by a real virtual machine layer and then let them have docker (or anything else) inside of that.  Obviously that completely defeats the light-weight win of running docker on a multi-user bare-metal server.  

Note that I believe the principle concern here applies to access to the docker daemon itself, not to user access inside the docker containers.  For instance, you could set up a bare-metal linux server, install docker daemon, and launch a container, rather than a full VM, for each user.  With an ssh-server installed on the container, users could ssh directly into their own container rather than the host machine.  I don't follow the security details closely, for a while there was some question of whether a user could break out of a container; but this may now be solved and was never the same kind of concern as accessing the docker daemon directly, which really does have immediate root access. 

Of course that doesn't let the user run docker inside their container.  Even though as of 1.8 you no longer need any heinous dind recipe (see: https://github.com/docker/docker/pull/15596) or the the `--privileged` flag, you do need to share access to the host's docker socket:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -ti ubuntu
```

which (after installing docker on the container) I believe gives you access to pretty-much the same things you could do using docker-engine from host (even though it requires starting the docker daemon separately on the container).  


Thanks for the link re user namespaces, hadn't seen that! apparently Feb 2016 isn't that far off.

**Comment by davclark** [comment]
Yeah - I think I'll need to work with trusted folks to provision trusted containers in a manner closer to the jupyter hub project. So, it seems something more general purpose (like BCE) is probably warranted here too...

**Comment by davclark** [comment]
Transferring to #21
